global:
  domain: argocd.sorel.dev
  affinity:
    nodeAffinity:
      matchExpressions:
        - key: homelab/role
          operator: In
          values:
            - core

configs:
  cm:
    kustomize.buildOptions: --enable-helm
